swagger: "2.0"
info:
  title: net ecg
  version: 1.0.0
paths:
  /subscribers:
    post:
      summary: Register a new user
      description: Endpoint to register a new user with name and email
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: User JSON Object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
            201:
              description: "User registration successful"
              schema:
                $ref: '#/definitions/User'
            400:
              description: Invalid request payload    
    get:
      summary: ask if user exists
      description: Endpoint to register a new user with name and email
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: Request User
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: User registration successful
          schema:
            $ref: '#/definitions/UserArray'
        400:
          description: Invalid request payload
definitions:  
  User:
    properties:
      name:
        type: string
        example: John Doe
      email:
        type: string
        format: email
        example: johndoe@example.com
  UserArray:
    type: array
    items: 
     $ref: '#/definitions/User'
