// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSubscribersHandlerFunc turns a function with the right signature into a get subscribers handler
type GetSubscribersHandlerFunc func(GetSubscribersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSubscribersHandlerFunc) Handle(params GetSubscribersParams) middleware.Responder {
	return fn(params)
}

// GetSubscribersHandler interface for that can handle valid get subscribers params
type GetSubscribersHandler interface {
	Handle(GetSubscribersParams) middleware.Responder
}

// NewGetSubscribers creates a new http.Handler for the get subscribers operation
func NewGetSubscribers(ctx *middleware.Context, handler GetSubscribersHandler) *GetSubscribers {
	return &GetSubscribers{Context: ctx, Handler: handler}
}

/*
	GetSubscribers swagger:route GET /subscribers getSubscribers

ask if user exists

Endpoint to register a new user with name and email
*/
type GetSubscribers struct {
	Context *middleware.Context
	Handler GetSubscribersHandler
}

func (o *GetSubscribers) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSubscribersParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
